### ISSUE TITLE
Module "types" and python script "types.py"

### ISSUE THREAD

**Issue by gryken2014** [metrasynth/sunvox-dll-python#4]
Hello,

- I just notice that in your python sources there is a file named "types.py".

- I just notice, that, since python v3.3, there is a new module named "types"

Is-this dangerous  (to make the wrong import)  ?

Python docs site
https://docs.python.org/3.5/library/types.html?highlight=types

Thanks for your job, with python.

**Comment by matthewryanscott** [comment]
Thanks for the positive feedback!

Regarding the `types` module, Python 3 introduces absolute imports by default.

If you add the following code to `sunvox/__init__.py`:

```
import types
print(types)
```

You'll get this output:

```
<module 'types' from '.../lib/python3.5/types.py'>
```

Worth noting you can explicitly use relative imports, e.g.

```
from . import types
print(types)
```

Yields:

```
<module 'sunvox.types' from '.../sunvox-dll-python/sunvox/types.py'>
```

Within the `sunvox.*` modules themselves, they just `import sunvox.types` whenever they want that module.
