### ISSUE TITLE
Single note example

### ISSUE THREAD

**Issue by coderofsalvation** [metrasynth/sunvox-dll-python#5]
Hi! First of all its great to see this effort concerning python+Sunvox :) 
Question: could you provide example code to load a. Sunvox file and trigger notes of a generator? 
(assuming the Sunvox file contains empty pattern(s)) 

Just like this (but without osc) : https://github.com/metrasynth/SunVOSC/blob/master/examples/singlenote.py

Kind regards

Leon

**Comment by matthewryanscott** [comment]
@coderofsalvation I am terribly sorry that your request fell by the wayside!

Here is a quick code example of loading one of the SunVox example projects, introspecting its modules, then playing some notes with one of them:

```python
>>> sv.init(None, 44100, 2, 0)
67843

>>> slot = sv.Slot('Kiberaver - Hard Motor.sunvox')

>>> slot.get_number_of_modules()
68

>>> [(x + 1, slot.get_module_name(x)) for x in range(slot.get_number_of_modules())]
[(1, b'Output'),
 (2, b'Glide'),
 (3, b'Generator2'),
 (4, b'MetaModule'),
 (5, b'Reverb2'),
 (6, b'Amplifier'),
 ...]
# Note: Module index is 1-based when sending events.

>>> notes = ['C4', 'G4', 'G3']
    glide = 2
    from time import sleep
    for note in notes:
        slot.send_event(0, getattr(sv.NOTECMD, note), 120, glide, 0, 0)
        sleep(0.5)
    slot.send_event(0, sv.NOTECMD.NOTE_OFF, 0, glide, 0, 0)
```
